name: CI# Gitlab yaml file
stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.44.1-jammy
  script:
    - npm ci
    - npm run test
    - |
      export token=$(curl -H "Content-Type: application/json" -X POST --data "{\"client_id\": \"$client_id\", \"client_secret\": \"$client_secret\" }" https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"')
      echo $token
      curl -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer $token"  --data @"./test-results/junit-report.xml" https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=HEHE
      echo "done"

