# name: Playwright Tests
# on:
#   push :
#    branches:
#    - main
  
# jobs:
#   e2e-tests:
#     runs-on: macos-latest
#     if: github.event.deployment_status.state == 'success'
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 18
    # - name: Install dependencies
    #   run: npm ci
    # - name: Install Playwright
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test
#       env:
#         CLIENT_SECRET: ${{ CLIENT_SECRET }}
#         CLIENT_ID: ${{ CLIENT_ID }}
#         run: 'curl -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer $token"  --data @"./test-results/junit-report.xml" https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=HEHE'






name: Trigger test
run-name: ${{ github.actor }} is testing out GitHub Actions on develop branch 🚀
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      PROJECT_KEY:
        description: The key of project
        type: string
        required: true
      TEST_EXECUTION_KEY:
        description: The key of test execution
        type: string
        required: false

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  Trigger-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: export NODE_OPTIONS="--max-old-space-size=3072"
      - run: yarn install
      - run: yarn build
      - run: sudo apt update && sudo apt install -y gettext
      - run: echo "success"
      - run: echo $CLIENT_ID
      - run: echo $CLIENT_SECRET
      - run: echo ${{ inputs.PROJECT_KEY }}
      - run: echo ${{ inputs.TEST_EXECUTION_KEY }}
      - run: curl -H "Content-Type:application/json" -X POST --data "{\"clientId\":\"858B2FC2EB8C4046A62F037E67C15D73\",\"clientSecret\":\"55ee0eac5205acb5cc9562c1f9b07dd1ec5123f9b6cd27ad8e9591ae9f1f1076\"}" https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"'
      - run: echo TOKEN=$(curl -H "Content-Type:application/json" -X POST --data "{\"clientId\":\"858B2FC2EB8C4046A62F037E67C15D73\",\"clientSecret\":\"55ee0eac5205acb5cc9562c1f9b07dd1ec5123f9b6cd27ad8e9591ae9f1f1076\"}" https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"') >> $GITHUB_ENV
      - run: echo ${{ env.TOKEN }}
      # - run: curl -X 'GET' 'https://kiet-le-dss-macbook-air.tail305ff.ts.net/ds/milestones?projectId=10003' -H 'accept:application/json' -H 'authorization:JWT ${{ env.TOKEN }}'
      # - run: curl -H "Content-Type:text/xml" -H "Authorization:JWT $token" --data @test-reports/junit-report.xml "https://kiet-le-dss-macbook-air.tail305ff.ts.net/ds/test-result/junit?projectKey=${PROJECT_KEY}&testExecutionKey=${TEST_EXECUTION_KEY}"